### ISSUE TITLE
Feature: Compress the surrealdb.wasm file to minimize the file size

### ISSUE THREAD

**Issue by limcheekin** [surrealdb/surrealdb.wasm#117]
### Is your feature request related to a problem?

I suggest compress the surrealdb.wasm to gzip file first then decompress it when loading in the web browser.

### Describe the solution

In the surrealdb.wasm 0.9.x released, I implemented the decompression using `fflate` package:
```
import * as fflate from "https://cdn.skypack.dev/fflate@0.8.0?min";

(async function loadWasm() {
  if (wasm !== undefined) return wasm;

  const input = new URL("surrealdb.wasm.gz", import.meta.url);
  const imports = __wbg_get_imports();
  const response = await fetch(input);

  __wbg_init_memory(imports);

  const data = new Uint8Array(await response.arrayBuffer());
  const decompressed_data = fflate.gunzipSync(data);
  const bytes = decompressed_data.buffer;

  const { instance, module } = await WebAssembly.instantiate(bytes, imports);

  console.log("Surreal had been initialized!");

  return __wbg_finalize_init(instance, module);
})();
```

### Alternative methods

Not applicable.

### SurrealDB version

surrealdb 2.0.4

### Contact Details

limcheekin@vobject.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @limcheekin, this is something we will not implement in the library, as not everybody may wish to have this behaviour. Instead, it's better to implement this either in your CDN or to utilize a compilation step with something like rollup to apply compression. Hope this helps!

**Comment by limcheekin** [comment]
@kearfy Appreciate if you could advise on how to implement it in the compilation step such as which code block to replace.

Thank you.
