### ISSUE TITLE
Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by christophermiles** [surrealdb/surrealdb.wasm#30]
I have run into several issues trying to use this package in an Electron environment, so I have now created a minimal Vue.js app with Vite to see if the issues are Electron related.

I am now encountering a different issue.

I have the following file, based on the example in the README:

```
import { Surreal } from 'surrealdb.wasm';

const db = new Surreal();

try {
    // Connect to the database
    await db.connect("indxdb");
} catch (e) {
    console.error("ERROR", e);
}

export default db
```

In my entry point file I have:

```
import { createApp } from 'vue'
import db from './db'
import './style.css'
import App from './App.vue'

createApp(App).mount('#app')
```

Running `yarn dev` I get a number of errors relating to top level await being used in `surrealdb.wasm/dist/full/index.js`

<img width="1720" alt="Screenshot 2023-07-19 at 1 39 22 pm" src="https://github.com/surrealdb/surrealdb.wasm/assets/1767439/160358e3-ebe2-403e-ad7b-334d67b0c090">

**Comment by christophermiles** [comment]
This was a Vite issue

**Comment by ibilux** [comment]
> This was a Vite issue

How did you solve this ?

**Comment by joeyame** [comment]
🙄 Gatekeeping sucks. At least saying it was a Vite issue pointed me in the right direction, but it takes two seconds to copy and paste the fix 🙄

For anyone who doesn't want their life wasted, here you go:
`vite.config.ts`
```Typescript
// https://vitejs.dev/config/
export default defineConfig({
  optimizeDeps: {
    esbuildOptions: {
      target: 'esnext',
    }
  },
  build: {
    target: 'esnext',
  },
  plugins: [
    svelte(),
  ],
  server: {
    fs: {
      // Allow serving files from one level up to the project root
      allow: ['../..'],
    },
  },
})
```

Not sure if the `build:target:esnext` is necessary, but the `optimizeDeps` is what made it start working for me.
