### ISSUE TITLE
Bug: Statement ONLY ignored - result is always an array

### ISSUE THREAD

**Issue by sebastianwessel** [surrealdb/surrealdb.wasm#36]
### Describe the bug

The newly introduced `ONLY` statement indicates that the result is a single result.
The result should not be wrapped into an extra array. 

### Steps to reproduce

```sql
--- without ONLY
CREATE test:1 SET some='value'
```
returns
```JSON
[
    {
        "id": "test:1",
        "some": "value"
    }
]
```

```sql
--- with ONLY
CREATE ONLY test:2 SET some='value'
```
returns
```JSON
[
    {
        "id": "test:2",
        "some": "value"
    }
]
```

### Expected behaviour

The behaviour should be the same as on the regular server

```sql
--- with ONLY
CREATE ONLY test:2 SET some='value'
```
returns
```JSON
{
    "id": "test:2",
    "some": "value"
}
```

Same for `SELECT` statement.

### SurrealDB version

local build from current master - surrealdb to beta.11 - on macOS

### Contact Details

mail@sebastianwessel.de

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Fixed by #43
