### ISSUE TITLE
Feature: relesse .wasm

### ISSUE THREAD

**Issue by gedw99** [surrealdb/surrealdb.wasm#37]
### Is your feature request related to a problem?

make it easy for non rust users to try this out.

### Describe the solution

Can we have a .wasm release out of GitHub workflow

https://github.com/surrealdb/surrealdb.wasm/releases

then we can build up usage examples for JS or typescript devs using it.

### Alternative methods

not applicable....

### SurrealDB version

all

### Contact Details

gedw99@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SuperPauly** [comment]
Agreed, or/and it would be nice to have the Rust build instructions for non Rust users.

**Comment by gedw99** [comment]
I can compile rust, but I wanted to use it from golang or js.
