### ISSUE TITLE
question: npm package is empty

### ISSUE THREAD

**Issue by sewe75** [surrealdb/surrealdb.wasm#4]
Started following the [docs](https://surrealdb.com/docs/integration/libraries/webassembly) but it seems the package published to npm is empty: https://www.npmjs.com/package/surrealdb.wasm

![image](https://user-images.githubusercontent.com/3164921/193567439-1fd07447-fee9-4091-84af-27406f392241.png)

Is this intended?  
Building and running locally works fine.

**Comment by mathe42** [comment]
Yes it is! If you want to use it you can use `mathe42.surrealdb.wasm`.

**Comment by ibilux** [comment]
> Yes it is! If you want to use it you can use `mathe42.surrealdb.wasm`.

Can you make a new release with latest branch ?

**Comment by ibilux** [comment]
> Started following the [docs](https://surrealdb.com/docs/integration/libraries/webassembly) but it seems the package published to npm is empty: https://www.npmjs.com/package/surrealdb.wasm
> 
> ![image](https://user-images.githubusercontent.com/3164921/193567439-1fd07447-fee9-4091-84af-27406f392241.png)
> 
> Is this intended? Building and running locally works fine.

There is a new release and it's working.

**Comment by kearfy** [comment]
We since did our first release of the library, I think the empty release was to claim the name for a bit. Thank you!
