### ISSUE TITLE
Feature: Closely matches the API of the Javascript library

### ISSUE THREAD

**Issue by ibilux** [surrealdb/surrealdb.wasm#40]
### Is your feature request related to a problem?

The `surrealdb.js` uses this code to connect:
```js
	// Signin as a namespace, database, or root user
	await db.signin({
		user: "root",
		pass: "root",
	});

	// Select a specific namespace / database
	await db.use({ ns: "test", db: "test" });
```
but the `surrealdb.wasm` uses this code to connect:
```js
	// Signin as a namespace, database, or root user
	await db.signin({
		username: "root",
		password: "root",
	});

	// Select a specific namespace / database
	await db.use({ namespace: "test", database: "test" });
```
Why not use the same params for closely matches the API of the Javascript library ?

### Describe the solution

Closely matches the API of the Javascript library using the same params to connect.

### Alternative methods

Use the same params for closely matches the API of the Javascript library ?

### SurrealDB version

1.0.0+20231002.920cdfc for linux on x86_64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Heya! We have since switched to full name parameters in the JS library, and have also made changes in #43 to make the interface more similar. Thanks!
