### ISSUE TITLE
Feature: Proper typings

### ISSUE THREAD

**Issue by orimay** [surrealdb/surrealdb.wasm#45]
### Is your feature request related to a problem?

I can see that the typings are generated automagically, but there's a bunch of `any`s and some function arguments are marked required (as addressed [here](https://github.com/surrealdb/surrealdb.wasm/issues/26)). It would've been nice to have proper typings for the library

### Describe the solution

Explicitly defined TS typings

### Alternative methods

Use as is or define custom typings

### SurrealDB version

surreal.wasm-v0.7.0

### Contact Details

dmitrii.a.baranov@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Fixed by #43
