### ISSUE TITLE
Feature: live queries

### ISSUE THREAD

**Issue by orimay** [surrealdb/surrealdb.wasm#46]
### Is your feature request related to a problem?

Currently, live queries are not supported

### Describe the solution

New API that would utilize async generators. It would've been awesome to have it [typed](https://github.com/surrealdb/surrealdb.wasm/issues/45)

### Alternative methods

Use with no live queries, just track updates out of database for local IndexDB cases

### SurrealDB version

surrealdb.wasm^0.7.0

### Contact Details

dmitrii.a.baranov@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by limcheekin** [comment]
May I know is there any update?

**Comment by phughk** [comment]
With the rust API now using live queries, this should be already working. 0.7.0 was released in September, so it doesn't include that functionality. Will ping the team about doing a new release of wasm. Closing as it is resolved. We can re-open a bug if it is still not working.

**Comment by phughk** [comment]
Re-opening, after having spoken to @rushmorem - turns out the wasm project does wrap the Rust API but needs explicit support for JS types, and that would be a feature. Going to add-assign to Rushmore as well

**Comment by limcheekin** [comment]
> With the rust API now using live queries, this should be already working. 0.7.0 was released in September, so it doesn't include that functionality. Will ping the team about doing a new release of wasm. Closing as it is resolved. We can re-open a bug if it is still not working.

Please release wasm for the SurrealDB v1.1 first. For other features, you can make it into v1. 2 release which is not so long to go anyway. 

Thank you.

**Comment by rushmorem** [comment]
`v0.8.0` is now out with support for the live query API. Unlike the Rust SDK though, it doesn't also have direct support for the `LIVE SELECT` statement in the `query` method yet.
